export const BUY_CAKE = "BUY_CAKE" ;
export const BUY_ICE_CREAM = "BUT_ICE_CREAM" ;
export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST" ;
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS" ;
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE" ;